### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by AntonKuzminRussia** [hsiafan/requests#25]
Hello. Big thanks to you for this best python-requests java analogue. I search it very long time. 
Today i found a NullPointerException bug with strange hosts answers.

> 	at java.util.Objects.requireNonNull(Objects.java:203)
	at net.dongliu.requests.executor.URLConnectionExecutor.getResponse(URLConnectionExecutor.java:286)
	at net.dongliu.requests.executor.URLConnectionExecutor.doRequest(URLConnectionExecutor.java:223)
	at net.dongliu.requests.executor.URLConnectionExecutor.proceed(URLConnectionExecutor.java:49)
	at net.dongliu.requests.InterceptorChain.proceed(InterceptorChain.java:24)
	at net.dongliu.requests.RequestBuilder.send(RequestBuilder.java:395)

I think problem in 

> Objects.requireNonNull(statusLine)

because some bug hosts don`t return status-line (non RFC complitable response). Examples:

> curl -vv http://217.114.100.158
> curl -vv http://217.112.3.116

**Comment by hsiafan** [comment]
I'm afraid this is not the only problem. The JDK's HttpURLConnection return status code -1 for this url, and no http body can be retrieved.
Removing the null check do not solve this issue.

**Comment by hsiafan** [comment]
Return null response is not good, maybe we can return a response with status code -1, and empty body.

**Comment by hsiafan** [comment]
fixed in version 4.18.1
